version: '3.3'

services:
  single-module-api-mysql:
    image: mysql:5.7
    container_name: single-module-api-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    restart: always
    ports:
      - '9040:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mystore
      TZ: Asia/Seoul
